import type { Metadata } from "next";
import "./globals.css";
import { font_default } from "@/lib/fonts";
import Decor from "@/components/UI/decor";
import Sloth from "@/components/3D/sloth";
import Header from "@/components/UI/header";

export const metadata: Metadata = {
  title: "Студия-LENIVEЦ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`antialiased`}>
      <body
        className={`w-full min-h-screen ${font_default.className} text-secondary`}
      >
        <Decor />
        <Header />
        {children}
        {/* <Sloth /> */}
      </body>
    </html>
  );
}
